// country code list with all country name, country code, two letter code, and flag based on https://en.wikipedia.org/wiki/List_of_country_calling_codes
export interface CountryCode { 
  code: string; // e.g. '+1'
  id: string; // e.g. 'US'
  flag: string; // e.g. '🇺🇸'
  name: string; // e.g. 'United States'
  mask: string; // e.g. '(###)-###-####'
} 


export const countryCodeList: CountryCode[] = [
    // Zone 1 - North American Numbering Plan (NANP)
    { code: '+1', id: 'US', flag: '🇺🇸', name: 'United States', mask: '(###)-###-####' },
    { code: '+1', id: 'CA', flag: '🇨🇦', name: 'Canada', mask: '(###)-###-####' },
    { code: '+1', id: 'AG', flag: '🇦🇬', name: 'Antigua and Barbuda', mask: '(###)-###-####' },
    { code: '+1', id: 'AI', flag: '🇦🇮', name: 'Anguilla', mask: '(###)-###-####' },
    { code: '+1', id: 'AS', flag: '🇦🇸', name: 'American Samoa', mask: '(###)-###-####' },
    { code: '+1', id: 'BS', flag: '🇧🇸', name: 'Bahamas', mask: '(###)-###-####' },
    { code: '+1', id: 'BB', flag: '🇧🇧', name: 'Barbados', mask: '(###)-###-####' },
    { code: '+1', id: 'BM', flag: '🇧🇲', name: 'Bermuda', mask: '(###)-###-####' },
    { code: '+1', id: 'VG', flag: '🇻🇬', name: 'British Virgin Islands', mask: '(###)-###-####' },
    { code: '+1', id: 'KY', flag: '🇰🇾', name: 'Cayman Islands', mask: '(###)-###-####' },
    { code: '+1', id: 'DM', flag: '🇩🇲', name: 'Dominica', mask: '(###)-###-####' },
    { code: '+1', id: 'DO', flag: '🇩🇴', name: 'Dominican Republic', mask: '(###)-###-####' },
    { code: '+1', id: 'GD', flag: '🇬🇩', name: 'Grenada', mask: '(###)-###-####' },
    { code: '+1', id: 'GU', flag: '🇬🇺', name: 'Guam', mask: '(###)-###-####' },
    { code: '+1', id: 'JM', flag: '🇯🇲', name: 'Jamaica', mask: '(###)-###-####' },
    { code: '+1', id: 'MS', flag: '🇲🇸', name: 'Montserrat', mask: '(###)-###-####' },
    { code: '+1', id: 'MP', flag: '🇲🇵', name: 'Northern Mariana Islands', mask: '(###)-###-####' },
    { code: '+1', id: 'PR', flag: '🇵🇷', name: 'Puerto Rico', mask: '(###)-###-####' },
    { code: '+1', id: 'KN', flag: '🇰🇳', name: 'Saint Kitts and Nevis', mask: '(###)-###-####' },
    { code: '+1', id: 'LC', flag: '🇱🇨', name: 'Saint Lucia', mask: '(###)-###-####' },
    { code: '+1', id: 'VC', flag: '🇻🇨', name: 'Saint Vincent and the Grenadines', mask: '(###)-###-####' },
    { code: '+1', id: 'SX', flag: '🇸🇽', name: 'Sint Maarten', mask: '(###)-###-####' },
    { code: '+1', id: 'TT', flag: '🇹🇹', name: 'Trinidad and Tobago', mask: '(###)-###-####' },
    { code: '+1', id: 'TC', flag: '🇹🇨', name: 'Turks and Caicos Islands', mask: '(###)-###-####' },
    { code: '+1', id: 'VI', flag: '🇻🇮', name: 'United States Virgin Islands', mask: '(###)-###-####' },
    // Zone 2 - Africa
    { code: '+20', id: 'EG', flag: '🇪🇬', name: 'Egypt', mask: '(###)-###-####' },
    { code: '+211', id: 'SS', flag: '🇸🇸', name: 'South Sudan', mask: '(###)-###-###' },
    { code: '+212', id: 'MA', flag: '🇲🇦', name: 'Morocco', mask: '(###)-###-###' },
    { code: '+212', id: 'EH', flag: '🇪🇭', name: 'Western Sahara', mask: '(###)-###-###' },
    { code: '+213', id: 'DZ', flag: '🇩🇿', name: 'Algeria', mask: '(###)-##-##-##' },
    { code: '+216', id: 'TN', flag: '🇹🇳', name: 'Tunisia', mask: '(##)-###-###' },
    { code: '+218', id: 'LY', flag: '🇱🇾', name: 'Libya', mask: '(##)-#######' },
    { code: '+220', id: 'GM', flag: '🇬🇲', name: 'Gambia', mask: '(###)-####' },
    { code: '+221', id: 'SN', flag: '🇸🇳', name: 'Senegal', mask: '(##)-###-##-##' },
    { code: '+222', id: 'MR', flag: '🇲🇷', name: 'Mauritania', mask: '(##)-##-##-##' },
    { code: '+223', id: 'ML', flag: '🇲🇱', name: 'Mali', mask: '(##)-##-##-##' },
    { code: '+224', id: 'GN', flag: '🇬🇳', name: 'Guinea', mask: '(###)-##-##-##' },
    { code: '+225', id: 'CI', flag: '🇨🇮', name: 'Ivory Coast', mask: '(##)-##-##-##' },
    { code: '+226', id: 'BF', flag: '🇧🇫', name: 'Burkina Faso', mask: '(##)-##-##-##' },
    { code: '+227', id: 'NE', flag: '🇳🇪', name: 'Niger', mask: '(##)-##-##-##' },
    { code: '+228', id: 'TG', flag: '🇹🇬', name: 'Togo', mask: '(##)-##-##-##' },
    { code: '+229', id: 'BJ', flag: '🇧🇯', name: 'Benin', mask: '(##)-##-##-##' },
    { code: '+230', id: 'MU', flag: '🇲🇺', name: 'Mauritius', mask: '(####)-####' },
    { code: '+231', id: 'LR', flag: '🇱🇷', name: 'Liberia', mask: '(###)-####' },
    { code: '+232', id: 'SL', flag: '🇸🇱', name: 'Sierra Leone', mask: '(##)-######' },
    { code: '+233', id: 'GH', flag: '🇬🇭', name: 'Ghana', mask: '(##)-###-####' },
    { code: '+234', id: 'NG', flag: '🇳🇬', name: 'Nigeria', mask: '(###)-###-####' },
    { code: '+235', id: 'TD', flag: '🇹🇩', name: 'Chad', mask: '(##)-##-##-##' },
    { code: '+236', id: 'CF', flag: '🇨🇫', name: 'Central African Republic', mask: '(##)-##-##-##' },
    { code: '+237', id: 'CM', flag: '🇨🇲', name: 'Cameroon', mask: '(##)-##-##-##' },
    { code: '+238', id: 'CV', flag: '🇨🇻', name: 'Cape Verde', mask: '(###)-##-##' },
    { code: '+239', id: 'ST', flag: '🇸🇹', name: 'São Tomé and Príncipe', mask: '(###)-####' },
    { code: '+240', id: 'GQ', flag: '🇬🇶', name: 'Equatorial Guinea', mask: '(###)-###-###' },
    { code: '+241', id: 'GA', flag: '🇬🇦', name: 'Gabon', mask: '(##)-##-##-##' },
    { code: '+242', id: 'CG', flag: '🇨🇬', name: 'Republic of the Congo', mask: '(##)-###-####' },
    { code: '+243', id: 'CD', flag: '🇨🇩', name: 'Democratic Republic of the Congo', mask: '(###)-###-###' },
    { code: '+244', id: 'AO', flag: '🇦🇴', name: 'Angola', mask: '(###)-###-###' },
    { code: '+245', id: 'GW', flag: '🇬🇼', name: 'Guinea-Bissau', mask: '(###)-####' },
    { code: '+246', id: 'IO', flag: '🇮🇴', name: 'British Indian Ocean Territory', mask: '(###)-####' },
    { code: '+247', id: 'AC', flag: '🇦🇨', name: 'Ascension Island', mask: '####' },
    { code: '+248', id: 'SC', flag: '🇸🇨', name: 'Seychelles', mask: '(#)-###-###' },
    { code: '+249', id: 'SD', flag: '🇸🇩', name: 'Sudan', mask: '(##)-###-####' },
    { code: '+250', id: 'RW', flag: '🇷🇼', name: 'Rwanda', mask: '(###)-###-###' },
    { code: '+251', id: 'ET', flag: '🇪🇹', name: 'Ethiopia', mask: '(##)-###-####' },
    { code: '+252', id: 'SO', flag: '🇸🇴', name: 'Somalia', mask: '(##)-###-####' },
    { code: '+253', id: 'DJ', flag: '🇩🇯', name: 'Djibouti', mask: '(##)-##-##-##' },
    { code: '+254', id: 'KE', flag: '🇰🇪', name: 'Kenya', mask: '(###)-######' },
    { code: '+255', id: 'TZ', flag: '🇹🇿', name: 'Tanzania', mask: '(###)-###-###' },
    { code: '+256', id: 'UG', flag: '🇺🇬', name: 'Uganda', mask: '(###)-######' },
    { code: '+257', id: 'BI', flag: '🇧🇮', name: 'Burundi', mask: '(##)-##-##-##' },
    { code: '+258', id: 'MZ', flag: '🇲🇿', name: 'Mozambique', mask: '(##)-###-####' },
    { code: '+260', id: 'ZM', flag: '🇿🇲', name: 'Zambia', mask: '(##)-###-####' },
    { code: '+261', id: 'MG', flag: '🇲🇬', name: 'Madagascar', mask: '(##)-##-###-##' },
    { code: '+262', id: 'RE', flag: '🇷🇪', name: 'Réunion', mask: '(###)-##-##-##' },
    { code: '+262', id: 'YT', flag: '🇾🇹', name: 'Mayotte', mask: '(###)-##-##-##' },
    { code: '+263', id: 'ZW', flag: '🇿🇼', name: 'Zimbabwe', mask: '(##)-###-####' },
    { code: '+264', id: 'NA', flag: '🇳🇦', name: 'Namibia', mask: '(##)-###-####' },
    { code: '+265', id: 'MW', flag: '🇲🇼', name: 'Malawi', mask: '(###)-##-##-##' },
    { code: '+266', id: 'LS', flag: '🇱🇸', name: 'Lesotho', mask: '(##)-###-###' },
    { code: '+267', id: 'BW', flag: '🇧🇼', name: 'Botswana', mask: '(##)-###-###' },
    { code: '+268', id: 'SZ', flag: '🇸🇿', name: 'Eswatini', mask: '(##)-##-####' },
    { code: '+269', id: 'KM', flag: '🇰🇲', name: 'Comoros', mask: '(###)-##-##' },
    { code: '+27', id: 'ZA', flag: '🇿🇦', name: 'South Africa', mask: '(##)-###-####' },
    { code: '+290', id: 'SH', flag: '🇸🇭', name: 'Saint Helena', mask: '#####' },
    { code: '+291', id: 'ER', flag: '🇪🇷', name: 'Eritrea', mask: '(#)-###-###' },
    { code: '+297', id: 'AW', flag: '🇦🇼', name: 'Aruba', mask: '(###)-####' },
    { code: '+298', id: 'FO', flag: '🇫🇴', name: 'Faroe Islands', mask: '(###)-###' },
    { code: '+299', id: 'GL', flag: '🇬🇱', name: 'Greenland', mask: '(##)-##-##' },
    // Zone 3 - Europe
    { code: '+30', id: 'GR', flag: '🇬🇷', name: 'Greece', mask: '(###)-###-####' },
    { code: '+31', id: 'NL', flag: '🇳🇱', name: 'Netherlands', mask: '(##)-###-####' },
    { code: '+32', id: 'BE', flag: '🇧🇪', name: 'Belgium', mask: '(###)-##-##-##' },
    { code: '+33', id: 'FR', flag: '🇫🇷', name: 'France', mask: '(#)-##-##-##-##' },
    { code: '+34', id: 'ES', flag: '🇪🇸', name: 'Spain', mask: '(###)-###-###' },
    { code: '+350', id: 'GI', flag: '🇬🇮', name: 'Gibraltar', mask: '#####' },
    { code: '+351', id: 'PT', flag: '🇵🇹', name: 'Portugal', mask: '(###)-###-###' },
    { code: '+352', id: 'LU', flag: '🇱🇺', name: 'Luxembourg', mask: '(###)-###-###' },
    { code: '+353', id: 'IE', flag: '🇮🇪', name: 'Ireland', mask: '(##)-###-####' },
    { code: '+354', id: 'IS', flag: '🇮🇸', name: 'Iceland', mask: '(###)-####' },
    { code: '+355', id: 'AL', flag: '🇦🇱', name: 'Albania', mask: '(###)-###-###' },
    { code: '+356', id: 'MT', flag: '🇲🇹', name: 'Malta', mask: '(####)-####' },
    { code: '+357', id: 'CY', flag: '🇨🇾', name: 'Cyprus', mask: '(##)-######' },
    { code: '+358', id: 'FI', flag: '🇫🇮', name: 'Finland', mask: '(##)-###-##-##' },
    { code: '+358', id: 'AX', flag: '🇦🇽', name: 'Åland Islands', mask: '(##)-###-##-##' },
    { code: '+359', id: 'BG', flag: '🇧🇬', name: 'Bulgaria', mask: '(##)-###-####' },
    { code: '+36', id: 'HU', flag: '🇭🇺', name: 'Hungary', mask: '(##)-###-####' },
    { code: '+370', id: 'LT', flag: '🇱🇹', name: 'Lithuania', mask: '(###)-##-###' },
    { code: '+371', id: 'LV', flag: '🇱🇻', name: 'Latvia', mask: '(##)-###-###' },
    { code: '+372', id: 'EE', flag: '🇪🇪', name: 'Estonia', mask: '(##)-###-###' },
    { code: '+373', id: 'MD', flag: '🇲🇩', name: 'Moldova', mask: '(##)-###-###' },
    { code: '+374', id: 'AM', flag: '🇦🇲', name: 'Armenia', mask: '(##)-###-###' },
    { code: '+375', id: 'BY', flag: '🇧🇾', name: 'Belarus', mask: '(##)-###-##-##' },
    { code: '+376', id: 'AD', flag: '🇦🇩', name: 'Andorra', mask: '(###)-###' },
    { code: '+377', id: 'MC', flag: '🇲🇨', name: 'Monaco', mask: '(##)-##-##-##' },
    { code: '+378', id: 'SM', flag: '🇸🇲', name: 'San Marino', mask: '(####)-######' },
    { code: '+380', id: 'UA', flag: '🇺🇦', name: 'Ukraine', mask: '(##)-###-##-##' },
    { code: '+381', id: 'RS', flag: '🇷🇸', name: 'Serbia', mask: '(##)-###-####' },
    { code: '+382', id: 'ME', flag: '🇲🇪', name: 'Montenegro', mask: '(##)-###-###' },
    { code: '+383', id: 'XK', flag: '🇽🇰', name: 'Kosovo', mask: '(##)-###-###' },
    { code: '+385', id: 'HR', flag: '🇭🇷', name: 'Croatia', mask: '(##)-###-###' },
    { code: '+386', id: 'SI', flag: '🇸🇮', name: 'Slovenia', mask: '(##)-###-###' },
    { code: '+387', id: 'BA', flag: '🇧🇦', name: 'Bosnia and Herzegovina', mask: '(##)-###-###' },
    { code: '+389', id: 'MK', flag: '🇲🇰', name: 'North Macedonia', mask: '(##)-###-###' },
    { code: '+39', id: 'IT', flag: '🇮🇹', name: 'Italy', mask: '(###)-###-####' },
    { code: '+39', id: 'VA', flag: '🇻🇦', name: 'Vatican City', mask: '(##)-####-####' },
    { code: '+40', id: 'RO', flag: '🇷🇴', name: 'Romania', mask: '(###)-###-###' },
    { code: '+41', id: 'CH', flag: '🇨🇭', name: 'Switzerland', mask: '(##)-###-##-##' },
    { code: '+420', id: 'CZ', flag: '🇨🇿', name: 'Czech Republic', mask: '(###)-###-###' },
    { code: '+421', id: 'SK', flag: '🇸🇰', name: 'Slovakia', mask: '(###)-###-###' },
    { code: '+423', id: 'LI', flag: '🇱🇮', name: 'Liechtenstein', mask: '(###)-####' },
    { code: '+43', id: 'AT', flag: '🇦🇹', name: 'Austria', mask: '(###)-###-####' },
    { code: '+44', id: 'GB', flag: '🇬🇧', name: 'United Kingdom', mask: '(####)-######' },
    { code: '+44', id: 'GG', flag: '🇬🇬', name: 'Guernsey', mask: '(####)-######' },
    { code: '+44', id: 'IM', flag: '🇮🇲', name: 'Isle of Man', mask: '(####)-######' },
    { code: '+44', id: 'JE', flag: '🇯🇪', name: 'Jersey', mask: '(####)-######' },
    { code: '+45', id: 'DK', flag: '🇩🇰', name: 'Denmark', mask: '(##)-##-##-##' },
    { code: '+46', id: 'SE', flag: '🇸🇪', name: 'Sweden', mask: '(##)-###-##-##' },
    { code: '+47', id: 'NO', flag: '🇳🇴', name: 'Norway', mask: '(###)-##-###' },
    { code: '+47', id: 'SJ', flag: '🇸🇯', name: 'Svalbard and Jan Mayen', mask: '(###)-##-###' },
    { code: '+48', id: 'PL', flag: '🇵🇱', name: 'Poland', mask: '(###)-###-###' },
    { code: '+49', id: 'DE', flag: '🇩🇪', name: 'Germany', mask: '(###)-#######' },
    // Zone 5 - Central & South America, Caribbean
    { code: '+500', id: 'FK', flag: '🇫🇰', name: 'Falkland Islands', mask: '#####' },
    { code: '+500', id: 'GS', flag: '🇬🇸', name: 'South Georgia and the South Sandwich Islands', mask: '#####' },
    { code: '+501', id: 'BZ', flag: '🇧🇿', name: 'Belize', mask: '(###)-####' },
    { code: '+502', id: 'GT', flag: '🇬🇹', name: 'Guatemala', mask: '(####)-####' },
    { code: '+503', id: 'SV', flag: '🇸🇻', name: 'El Salvador', mask: '(####)-####' },
    { code: '+504', id: 'HN', flag: '🇭🇳', name: 'Honduras', mask: '(####)-####' },
    { code: '+505', id: 'NI', flag: '🇳🇮', name: 'Nicaragua', mask: '(####)-####' },
    { code: '+506', id: 'CR', flag: '🇨🇷', name: 'Costa Rica', mask: '(####)-####' },
    { code: '+507', id: 'PA', flag: '🇵🇦', name: 'Panama', mask: '(####)-####' },
    { code: '+508', id: 'PM', flag: '🇵🇲', name: 'Saint Pierre and Miquelon', mask: '(##)-##-##' },
    { code: '+509', id: 'HT', flag: '🇭🇹', name: 'Haiti', mask: '(##)-##-####' },
    { code: '+51', id: 'PE', flag: '🇵🇪', name: 'Peru', mask: '(###)-###-###' },
    { code: '+52', id: 'MX', flag: '🇲🇽', name: 'Mexico', mask: '(##)-####-####' },
    { code: '+53', id: 'CU', flag: '🇨🇺', name: 'Cuba', mask: '(#)-###-####' },
    { code: '+54', id: 'AR', flag: '🇦🇷', name: 'Argentina', mask: '(##)-####-####' },
    { code: '+55', id: 'BR', flag: '🇧🇷', name: 'Brazil', mask: '(##)-#####-####' },
    { code: '+56', id: 'CL', flag: '🇨🇱', name: 'Chile', mask: '(#)-####-####' },
    { code: '+57', id: 'CO', flag: '🇨🇴', name: 'Colombia', mask: '(###)-###-####' },
    { code: '+58', id: 'VE', flag: '🇻🇪', name: 'Venezuela', mask: '(###)-###-####' },
    { code: '+590', id: 'GP', flag: '🇬🇵', name: 'Guadeloupe', mask: '(###)-##-##-##' },
    { code: '+590', id: 'BL', flag: '🇧🇱', name: 'Saint Barthélemy', mask: '(###)-##-##-##' },
    { code: '+590', id: 'MF', flag: '🇲🇫', name: 'Saint Martin', mask: '(###)-##-##-##' },
    { code: '+591', id: 'BO', flag: '🇧🇴', name: 'Bolivia', mask: '(#)-###-####' },
    { code: '+592', id: 'GY', flag: '🇬🇾', name: 'Guyana', mask: '(###)-####' },
    { code: '+593', id: 'EC', flag: '🇪🇨', name: 'Ecuador', mask: '(##)-###-####' },
    { code: '+594', id: 'GF', flag: '🇬🇫', name: 'French Guiana', mask: '(###)-##-##-##' },
    { code: '+595', id: 'PY', flag: '🇵🇾', name: 'Paraguay', mask: '(###)-###-###' },
    { code: '+596', id: 'MQ', flag: '🇲🇶', name: 'Martinique', mask: '(###)-##-##-##' },
    { code: '+597', id: 'SR', flag: '🇸🇷', name: 'Suriname', mask: '(###)-####' },
    { code: '+598', id: 'UY', flag: '🇺🇾', name: 'Uruguay', mask: '(#)-###-##-##' },
    { code: '+599', id: 'CW', flag: '🇨🇼', name: 'Curaçao', mask: '(###)-####' },
    { code: '+599', id: 'BQ', flag: '🇧🇶', name: 'Caribbean Netherlands', mask: '(###)-####' },
    // Zone 6 - Southeast Asia & Oceania
    { code: '+60', id: 'MY', flag: '🇲🇾', name: 'Malaysia', mask: '(##)-####-####' },
    { code: '+61', id: 'AU', flag: '🇦🇺', name: 'Australia', mask: '(###)-###-###' },
    { code: '+61', id: 'CX', flag: '🇨🇽', name: 'Christmas Island', mask: '(###)-###-###' },
    { code: '+61', id: 'CC', flag: '🇨🇨', name: 'Cocos (Keeling) Islands', mask: '(###)-###-###' },
    { code: '+62', id: 'ID', flag: '🇮🇩', name: 'Indonesia', mask: '(###)-####-####' },
    { code: '+63', id: 'PH', flag: '🇵🇭', name: 'Philippines', mask: '(###)-###-####' },
    { code: '+64', id: 'NZ', flag: '🇳🇿', name: 'New Zealand', mask: '(##)-###-####' },
    { code: '+64', id: 'PN', flag: '🇵🇳', name: 'Pitcairn Islands', mask: '(####)-####' },
    { code: '+65', id: 'SG', flag: '🇸🇬', name: 'Singapore', mask: '(####)-####' },
    { code: '+66', id: 'TH', flag: '🇹🇭', name: 'Thailand', mask: '(##)-###-####' },
    { code: '+670', id: 'TL', flag: '🇹🇱', name: 'Timor-Leste', mask: '(###)-####' },
    { code: '+672', id: 'NF', flag: '🇳🇫', name: 'Norfolk Island', mask: '(##)-####' },
    { code: '+673', id: 'BN', flag: '🇧🇳', name: 'Brunei', mask: '(###)-####' },
    { code: '+674', id: 'NR', flag: '🇳🇷', name: 'Nauru', mask: '(###)-####' },
    { code: '+675', id: 'PG', flag: '🇵🇬', name: 'Papua New Guinea', mask: '(##)-###-###' },
    { code: '+676', id: 'TO', flag: '🇹🇴', name: 'Tonga', mask: '(###)-####' },
    { code: '+677', id: 'SB', flag: '🇸🇧', name: 'Solomon Islands', mask: '(###)-####' },
    { code: '+678', id: 'VU', flag: '🇻🇺', name: 'Vanuatu', mask: '(###)-####' },
    { code: '+679', id: 'FJ', flag: '🇫🇯', name: 'Fiji', mask: '(###)-####' },
    { code: '+680', id: 'PW', flag: '🇵🇼', name: 'Palau', mask: '(###)-####' },
    { code: '+681', id: 'WF', flag: '🇼🇫', name: 'Wallis and Futuna', mask: '(##)-####' },
    { code: '+682', id: 'CK', flag: '🇨🇰', name: 'Cook Islands', mask: '(##)-###' },
    { code: '+683', id: 'NU', flag: '🇳🇺', name: 'Niue', mask: '####' },
    { code: '+685', id: 'WS', flag: '🇼🇸', name: 'Samoa', mask: '(##)-#####' },
    { code: '+686', id: 'KI', flag: '🇰🇮', name: 'Kiribati', mask: '(##)-##-###' },
    { code: '+687', id: 'NC', flag: '🇳🇨', name: 'New Caledonia', mask: '(##)-##-##' },
    { code: '+688', id: 'TV', flag: '🇹🇻', name: 'Tuvalu', mask: '(##)-###' },
    { code: '+689', id: 'PF', flag: '🇵🇫', name: 'French Polynesia', mask: '(##)-##-##-##' },
    { code: '+690', id: 'TK', flag: '🇹🇰', name: 'Tokelau', mask: '####' },
    { code: '+691', id: 'FM', flag: '🇫🇲', name: 'Micronesia', mask: '(###)-####' },
    { code: '+692', id: 'MH', flag: '🇲🇭', name: 'Marshall Islands', mask: '(###)-####' },
    // Zone 7 - Russia & Kazakhstan
    { code: '+7', id: 'RU', flag: '🇷🇺', name: 'Russia', mask: '(###)-###-##-##' },
    { code: '+7', id: 'KZ', flag: '🇰🇿', name: 'Kazakhstan', mask: '(###)-###-##-##' },
    // Zone 8 - East Asia
    { code: '+81', id: 'JP', flag: '🇯🇵', name: 'Japan', mask: '(##)-####-####' },
    { code: '+82', id: 'KR', flag: '🇰🇷', name: 'South Korea', mask: '(##)-####-####' },
    { code: '+84', id: 'VN', flag: '🇻🇳', name: 'Vietnam', mask: '(###)-###-####' },
    { code: '+850', id: 'KP', flag: '🇰🇵', name: 'North Korea', mask: '(###)-###-####' },
    { code: '+852', id: 'HK', flag: '🇭🇰', name: 'Hong Kong', mask: '(####)-####' },
    { code: '+853', id: 'MO', flag: '🇲🇴', name: 'Macau', mask: '(####)-####' },
    { code: '+855', id: 'KH', flag: '🇰🇭', name: 'Cambodia', mask: '(##)-###-###' },
    { code: '+856', id: 'LA', flag: '🇱🇦', name: 'Laos', mask: '(##)-###-####' },
    { code: '+86', id: 'CN', flag: '🇨🇳', name: 'China', mask: '(###)-####-####' },
    { code: '+880', id: 'BD', flag: '🇧🇩', name: 'Bangladesh', mask: '(##)-####-####' },
    { code: '+886', id: 'TW', flag: '🇹🇼', name: 'Taiwan', mask: '(###)-###-####' },
    // Zone 9 - South Asia, Middle East & Central Asia
    { code: '+90', id: 'TR', flag: '🇹🇷', name: 'Turkey', mask: '(###)-###-##-##' },
    { code: '+91', id: 'IN', flag: '🇮🇳', name: 'India', mask: '(#####)-#####' },
    { code: '+92', id: 'PK', flag: '🇵🇰', name: 'Pakistan', mask: '(###)-###-####' },
    { code: '+93', id: 'AF', flag: '🇦🇫', name: 'Afghanistan', mask: '(##)-###-####' },
    { code: '+94', id: 'LK', flag: '🇱🇰', name: 'Sri Lanka', mask: '(##)-###-####' },
    { code: '+95', id: 'MM', flag: '🇲🇲', name: 'Myanmar', mask: '(##)-###-####' },
    { code: '+960', id: 'MV', flag: '🇲🇻', name: 'Maldives', mask: '(###)-####' },
    { code: '+961', id: 'LB', flag: '🇱🇧', name: 'Lebanon', mask: '(##)-###-###' },
    { code: '+962', id: 'JO', flag: '🇯🇴', name: 'Jordan', mask: '(##)-###-####' },
    { code: '+963', id: 'SY', flag: '🇸🇾', name: 'Syria', mask: '(###)-###-###' },
    { code: '+964', id: 'IQ', flag: '🇮🇶', name: 'Iraq', mask: '(###)-###-####' },
    { code: '+965', id: 'KW', flag: '🇰🇼', name: 'Kuwait', mask: '(####)-####' },
    { code: '+966', id: 'SA', flag: '🇸🇦', name: 'Saudi Arabia', mask: '(##)-###-####' },
    { code: '+967', id: 'YE', flag: '🇾🇪', name: 'Yemen', mask: '(###)-###-###' },
    { code: '+968', id: 'OM', flag: '🇴🇲', name: 'Oman', mask: '(####)-####' },
    { code: '+970', id: 'PS', flag: '🇵🇸', name: 'Palestinian Territories', mask: '(##)-###-####' },
    { code: '+971', id: 'AE', flag: '🇦🇪', name: 'United Arab Emirates', mask: '(##)-###-####' },
    { code: '+972', id: 'IL', flag: '🇮🇱', name: 'Israel', mask: '(##)-###-####' },
    { code: '+973', id: 'BH', flag: '🇧🇭', name: 'Bahrain', mask: '(####)-####' },
    { code: '+974', id: 'QA', flag: '🇶🇦', name: 'Qatar', mask: '(####)-####' },
    { code: '+975', id: 'BT', flag: '🇧🇹', name: 'Bhutan', mask: '(##)-###-###' },
    { code: '+976', id: 'MN', flag: '🇲🇳', name: 'Mongolia', mask: '(####)-####' },
    { code: '+977', id: 'NP', flag: '🇳🇵', name: 'Nepal', mask: '(##)-###-####' },
    { code: '+98', id: 'IR', flag: '🇮🇷', name: 'Iran', mask: '(###)-###-####' },
    { code: '+992', id: 'TJ', flag: '🇹🇯', name: 'Tajikistan', mask: '(##)-###-####' },
    { code: '+993', id: 'TM', flag: '🇹🇲', name: 'Turkmenistan', mask: '(##)-###-####' },
    { code: '+994', id: 'AZ', flag: '🇦🇿', name: 'Azerbaijan', mask: '(##)-###-##-##' },
    { code: '+995', id: 'GE', flag: '🇬🇪', name: 'Georgia', mask: '(###)-###-###' },
    { code: '+996', id: 'KG', flag: '🇰🇬', name: 'Kyrgyzstan', mask: '(###)-###-###' },
    { code: '+998', id: 'UZ', flag: '🇺🇿', name: 'Uzbekistan', mask: '(##)-###-##-##' },
];
